---
# tasks file for web
  - name: install apache and php last version
    apt:
      name:
        - apache2
        - php
        - php-mysql
      state: present
      update_cache: yes
    when: ansible_facts['os_family']=="Debian"


  - name: install extra pckages
    apt:
      name: "{{extra_packages_debian}}"
      state: present
    when: ansible_facts['os_family']=="Debian"

  - name: add users
    user:
      name: "{{ item }}"
      state: present
    loop:
      - user1
      - user2

  - name: Give writable mode to http folder
    file:
      path: /var/www/html
      state: directory
      mode: '0755'


  - name: remove default index.html
    file:
      path: /var/www/html/index.html
      state: absent

  - name: upload web app source
    copy:
      src: app/
      dest: /var/www/html/

  - name: deploy php database config
    template:
      src: "db-config.php.j2"
      dest: "/var/www/html/db-config.php"
  
  - name: ensure apache service is start
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_facts['os_family']=="Debian"