---

# WEB SERVER
- hosts: web
  become: true
  vars_files: 
   - vars/main.yml
   - vars/mysql-users.yml

  roles:
   - web

# DATABASE SERVER

- hosts: db
  become: true
  vars_files: 
   - vars/main.yml
   - vars/mysql-users.yml
  vars:
    root_password: "my_secret_password"

  roles:
   - database



