apiVersion: v1
kind: Pod
metadata:
  name: multic
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "44Mi"
          cpu: "80m"
        limits:
          memory: "68Mi"
          cpu: "100m"
    - name: alpine
      image: alpine
      volumeMounts:
      - name: html
        mountPath: /html
      command: ["/bin/sh", "-c"]
      args:
        - date >> /html/index.html;
          while true; do
            sleep 1;
          done
      resources:
        requests:
          memory: "44Mi"
          cpu: "80m"
        limits:
          memory: "68Mi"
          cpu: "100m"
  volumes:
  - name: html
    hostPath: 
      path: /data
      type: DirectoryOrCreate