---
- name: playbook for failure
  hosts: client
  tasks:
    - name: run a script
      command: echo hello 
      ignore_errors: yes
      register: command_result
      failed_when: "'world' in command_result.stout"
    - name: see if we get here
      debug:
        msg: we got here 