---
- name: variables play book
  hosts: client
  gather_facts: no 
  vars_prompt: 
  - name: package
    prompt: whiche package
    private: no

  tasks:
    - name: install package {{package}}
      package:
        name: "{{package}}"  
        state: latest