- name: httpd
  hosts: client
  tasks:
    - name: install httpd
      package:
        name: vim
        state: latest
    - name: start httpd
      service:
        name: httpd
        state: started
        enabled: yes



